<a href="https://colab.research.google.com/github/VioletLiu0620/deeplearning/blob/main/00_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. Fundamentals

Hello!!

In [ ]:
import torch
import pandas as pd
import numpy as np

print(torch.__version__)

2.11.0+cu128


In [ ]:
!nvidia-smi

Fri Jul  3 10:48:05 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   35C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [ ]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim
# back to python

0

In [ ]:
scalar.item()

7

In [ ]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim
# dimension = # of square bracket

1

In [ ]:
vector.shape
# two things horizontally

torch.Size([2])

In [ ]:
matrix = torch.tensor([[7,8], [9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
matrix.ndim

2

In [ ]:
matrix.shape

torch.Size([2, 2])

In [ ]:
matrix1 = torch.tensor([[[7,8]]])
matrix1

tensor([[[7, 8]]])

In [ ]:
matrix1.ndim

3

In [ ]:
matrix1.shape

torch.Size([1, 1, 2])

In [ ]:
#TENSOR

matrix2 = torch.tensor([7, 7, 1])

matrix2

tensor([7, 7, 1])

In [ ]:
matrix2.ndim

1

In [ ]:
matrix2.shape

torch.Size([3])

In [ ]:
matrix2[0]

tensor(7)

In [ ]:
matrix3 = torch.tensor([[[1, 2, 3],
                         [4, 5, 6],
                         [7, 8, 9]]])
matrix3

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
matrix3.shape
# 1, 3x3 tensor

torch.Size([1, 3, 3])

In [ ]:
matrix3[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
matrix3.ndim

3

In [ ]:
matrix3[0][0]

tensor([1, 2, 3])

In [ ]:
matrix4 = torch.tensor([[[],[],[1, [3, 4, 5]]]])

In [ ]:
matrix4.ndim

3

In [ ]:
matrix4.shape

torch.Size([1, 3, 0])

In [ ]:
matrix4[0][2]

tensor([])

In [ ]:
matrix5 = torch.tensor([[1, 2, 3], []])

# got an error, the length of element at every level must match

ValueError: expected sequence of length 3 at dim 1 (got 0)

In [ ]:
matrix6 = torch.tensor([[1, 2, 3], [4, 5]])

In [ ]:
matrix7 = torch.tensor([[1, 2, 3], [4, 5, 6]])
matrix7

In [ ]:
matrix8 = torch.tensor([[], [4, 5, 6]])
matrix8
# but if you put empty on the first one, it get ignored, start assuming all the other elements on this level is also empty list, can passed but the [1, 2, 3] never get read

### Random tensors

Random tensors are important because the way m any neural netwroks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`



In [ ]:
# create a random tensor of size (3,4)

random = torch.rand(1, 2, 3, 4)
random

In [ ]:
random.ndim

In [ ]:
# Create a ranodm tensor with similar shpae to an image tensor
random_image = torch.rand(size = (3, 224,224,3)) #colour channel (RGB), height, width
random_image.shape, random_image.ndim

 ### Zeros and Ones

In [ ]:
zeros = torch.zeros(size=(3, 4))
zeros

In [ ]:
ones = torch.ones(size=(3,4))
ones

In [ ]:
ones.dtype
# default data type

### creating a rnago of tensors and tensors-like

In [ ]:
# Use torch.arange()
one_to_ten = torch.arange(0, 10)
one_to_ten

In [ ]:
arange1 = torch.arange(start=0, end= 101, step=25)
arange1

In [ ]:
# input is a tensor
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

In [ ]:
random1 = torch.rand(1, 2, 2)
like1 = torch.zeros_like(random1)
like1

### Tensor datatypes

In [ ]:
# float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # what datatype is the tensor (e.g. float32 or float16)
                               device="cuda", # what device is your tensor on
                               requires_grad=False) # whether or not to track gradients with this tensor operations
float_32_tensor

tensor([3., 6., 9.], device='cuda:0')

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], device='cuda:0', dtype=torch.float16)

In [ ]:
result = float_16_tensor * float_32_tensor

In [ ]:
result.dtype

torch.float32

### Getting information from tensor

1. tensors not the right type - use `tensor.dtype`
2. tensors not right shape - use `tensor.shape`
3. tensors not on the right device - use `tensor.device`

In [ ]:
print(f"Shape of tensor: {result.shape}")
print(f"Datatype of tensor: {result.dtype}")
print(f"Device of tensor: {result.device}")

Shape of tensor: torch.Size([3])
Datatype of tensor: torch.float32
Device of tensor: cuda:0


### Manipulating tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Mutiplication (element-wise)
* Division
* Matrix multiplication

In [ ]:
# Create a tensor
tensor = torch.tensor([1, 2, 3])
tensor = tensor + 10
tensor

tensor([11, 12, 13])

In [ ]:
# Mutiply tensor by 10
tensor = tensor * 10
tensor

tensor([110, 120, 130])

In [ ]:
# Subtract by 10
tensor = tensor - 10
tensor

tensor([100, 110, 120])

In [ ]:
# Divide by 10
tensor = tensor / 10
tensor

tensor([10., 11., 12.])

### Matrix multiplication

1. Element wise
2. matrix multiplication dot product

In [ ]:
print(tensor, "*", tensor)
print(f"Equals: {tensor*tensor}")
print("")
print(tensor, "*", 2)
print(f"Equals: {tensor*2}")

tensor([10., 11., 12.]) * tensor([10., 11., 12.])
Equals: tensor([100., 121., 144.])

tensor([10., 11., 12.]) * 2
Equals: tensor([20., 22., 24.])


In [ ]:
torch.matmul(tensor, tensor)

# if has a built-in torch version, usually faster

tensor(365.)

In [ ]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value.item())

365.0
CPU times: user 1.22 ms, sys: 19 µs, total: 1.24 ms
Wall time: 1.35 ms


In [ ]:
%%time
value = torch.matmul(tensor, tensor)
print(value.item())

365.0
CPU times: user 846 µs, sys: 74 µs, total: 920 µs
Wall time: 1.25 ms


### One of the msot common errors in deep learnings: shape error

(# of rows, # of coloumns)

1. The **inner dimension** must match:

* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work

2. The resulting matrix has the shape of the **outer dimensions**:

* `(2, 3) @ (3, 2)` will work, and result on a shape of 2, 2

In [ ]:
tensor_A = torch.tensor([[1, 2],
                        [3, 4],
                        [5, 6]])

tensor_B = torch.tensor([[7, 10],
                        [8, 11],
                        [9, 12]])

# we can use the abbreviation of torch.mm instead of torch.matmul
torch.mm(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
# use transpost with .T
tensor_B, tensor_B.T, tensor_B.T.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

## Finding the min, max, mean, sum, etc (tensor aggregation)

In [ ]:
# Create a tensor

x = torch.arange(0, 100, 10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [ ]:
torch.min(x)

tensor(0)

In [ ]:
x.min()

tensor(0)

In [ ]:
torch.max(x), x.max()

(tensor(90), tensor(90))

In [ ]:
torch.mean(x.type(torch.float32))
# the torch.mean() function requires a tensor of float32 datatype to work
# Data type error, need to change the type from long to something else

tensor(45.)

In [ ]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

# Find the index position of the min or max value

In [ ]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
x.argmin(), torch.argmin(x)

(tensor(0), tensor(0))

In [ ]:
y = torch.arange(10, 1, -1)
y

tensor([10,  9,  8,  7,  6,  5,  4,  3,  2])

In [ ]:
torch.argmin(y)

tensor(8)

In [ ]:
torch.argmax(y)

tensor(0)

## Reshaping, stacking, squeezing and unsequeezing tensors

* Reshaping - reshaping an input tensor to a defined shape
* View - Return a view of a input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine mutiple tensors on top of each other  (vstack) or side b side (hstack)
* Squeeze - remove all `i` dimensions from a tensor
* Unsqueeze - add a `i` dimensiosn to a tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [ ]:
import torch
x = torch.arange(1. ,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# the reshape has to be compatible, adding new square bracket is ok, but the # of element in the original tensor must be able to fit in the new size, 1x10 to 5x2 is ok, but no creation of new element

x_reshaped = x.reshape(9,1,1)
x_reshaped, x_reshaped.shape

(tensor([[[1.]],
 
         [[2.]],
 
         [[3.]],
 
         [[4.]],
 
         [[5.]],
 
         [[6.]],
 
         [[7.]],
 
         [[8.]],
 
         [[9.]]]),
 torch.Size([9, 1, 1]))

In [ ]:
# change the view
z = x_reshaped.view(9,1)
z, z.shape

## Changing z changes x (because a view of a tensor shares the same memory as the original tensor)

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [ ]:
z[:, 0 ] = 5
z, x_reshaped

(tensor([[5.],
         [5.],
         [5.],
         [5.],
         [5.],
         [5.],
         [5.],
         [5.],
         [5.]]),
 tensor([[[5.]],
 
         [[5.]],
 
         [[5.]],
 
         [[5.]],
 
         [[5.]],
 
         [[5.]],
 
         [[5.]],
 
         [[5.]],
 
         [[5.]]]))

In [ ]:
# Stack tensors on top of each other
x
x_stacked = torch.stack([x, x, x])
x_stacked

tensor([[5., 5., 5., 5., 5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5., 5., 5., 5., 5.]])

In [ ]:
# torch.squeeze() - removes all single dimensions from a target tensor
y = torch.arange(0,10,dtype= torch.float32)
y = y.reshape(1,10)
y

tensor([[0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
y.shape

torch.Size([1, 10])

In [ ]:
y.squeeze()

tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
y.squeeze().shape

torch.Size([10])

In [ ]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specfic dim
print(f"Previous target: {y.squeeze()}")
print(f"Previous shape: {y.squeeze().shape}")

x_unsqueezed = y.squeeze().unsqueeze(dim=0)
print(f"New target: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous target: tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([10])
New target: tensor([[0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 10])


In [ ]:
# From pytorch

x = torch.zeros(2, 1, 2)
x, x.size()

(tensor([[[0., 0.]],
 
         [[0., 0.]]]),
 torch.Size([2, 1, 2]))

In [ ]:
y = torch.squeeze(x)
y, y.size()

(tensor([[0., 0.],
         [0., 0.]]),
 torch.Size([2, 2]))

In [ ]:
y = torch.squeeze(x,dim=0)
y, y.size()

(tensor([[[0., 0.]],
 
         [[0., 0.]]]),
 torch.Size([2, 1, 2]))

squeezing must not change the data — it only removes a redundant "wrapper."

only size 1 dimension get squeezed, if it's not 1, it get ignored even you specified the dimension to be dim=x

**no dim given: remove ALL size-1 dims**

In [ ]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order

x_original = torch.rand(size=(224,224,3)) # height, width, colour_channels

# permute the original tensor to rearrange the axis or dim order
# switch the colour channel to the first

x_permuted = x_original.permute(2, 0 ,1) # shift the order 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [ ]:
x_original[0,0,0] = 12345
x_original[0,0,0], x_permuted[0,0,0]

(tensor(12345.), tensor(12345.))

## Indexing (selecting data from tensors)

indexing with pytorch is similar with numpy

In [ ]:
# create a tensor

import torch
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
x[0], x[0].ndim

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 2)

In [ ]:
# index on the middle bracket
x[0][0], x[0,0]

(tensor([1, 2, 3]), tensor([1, 2, 3]))

In [ ]:
# index on the most inner bracket
x[0][0][0]

tensor(1)

In [ ]:
x[:, :, 2]

tensor([[3, 6, 9]])

In [ ]:
x[0, 2, 2]

tensor(9)

## PyTorch tensors & Numpy

NumPy is a popular scientific python numerical computing library.

* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> Numpy -> `torch.Tensor.numpy()`

In [ ]:
# Numpy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)

# warning, when converting from numpy -> pytorch, pytorch reflects numpy's default datatype of float64 unless specified

array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
array.dtype

dtype('float64')

In [ ]:
tensor.dtype

torch.float64

In [ ]:
# Change the value of array
array = array + 1
array, tensor

# the new tensor didn't change, when use from_numpy, create one new in the memory

(array([3., 4., 5., 6., 7., 8., 9.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# Tensor to Numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
# Change the tensor, what happen to NumPy tensor?
tensor = tensor + 1
tensor, numpy_tensor

# the new tensor didn't change, don't share memory

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducbility (trying to take random out of random)

In short, how a nerual network learns:

`start with random numbers -> tensor operations -> update random numbers to try and make them better represenation of the data -> again -> again -> again...`

to reduce the randomness in neural netwroks and PyTorch comes the conept of a **random seed**

what the random seed does is "flavour" the randomness

In [ ]:
import torch

# Create two random tensors
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)
random_tensor_A, random_tensor_B

(tensor([[0.1850, 0.6345, 0.4577, 0.5240],
         [0.1355, 0.1752, 0.4007, 0.9523],
         [0.8308, 0.7277, 0.3954, 0.9335]]),
 tensor([[0.4552, 0.0508, 0.4490, 0.6256],
         [0.7056, 0.9770, 0.3202, 0.6118],
         [0.3387, 0.8423, 0.9562, 0.3198]]))

In [ ]:
print(random_tensor_B == random_tensor_A)

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# Let's make some random but reproducible tensors
import torch

# Set the random seed
RANDOM_SEED = 42
# answer to the univers because it sounded funny??
# random seed: you get the same value if random seed value is the same
# be able to reproduce the same tensor even when refreshing the page
# for example, random_seed = 42 -> [0][0][0] = 0.8823 as always

torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


 ## Running tensors and PyTorch objects on the GPUs (and making daster computataions)

 GPUs = faster computation on numbers, thanks to CUDA + NVIDIA hardware + PyTorch working behind the scenes to amke everything hunky dory (good).

### 1. Getting a GPU

1. Easiest - Use Google Colab for a free GPU
2. Use your own GPU - takes a little a bit of setup and requries set up
3. Use clou scomputing = GCP, AWS, Azures, these services allow you to rent computers on the cloud and access them

For 2, 3 PyTorch + GPU drivers (CUDA) takes a little bit of setting up, to do this, refer to PyTorch set up documentation

In [ ]:
!nvidia-smi

Sat Jul  4 09:14:44 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   37C    P8             11W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

### 2. Check for GPU access with PyTorch

In [ ]:
# Check for GPU access with PyTorch
import torch
torch.cuda.is_available()

True

In [ ]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
# Count number of devices
torch.cuda.device_count()

# Run one model on one GPU, run the other on other GPU

1

## 3. Putting tensors (and models) on the GPU

The reason we want our tensors/models on the GPU is because using a GPU results in faster computationss

In [ ]:
# Create a tensor (default is on the CPU)
tensor = torch.tensor([1,2,3])

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
# Move tensor to GPU (if available) use the .to()
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### 4. Moving tensors back to the CPU

In [ ]:
# If the tensor is on GPU, can't transform it to Numpy

tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [ ]:
# To fix the GPU tensor with Numpy issue, we can first set it ot the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [ ]:
tensor1 = np.arange(1.0,3.0)
tensor1

array([1., 2.])

In [ ]:
tensor1.dtype

dtype('float64')

In [ ]:
tensor2 = torch.from_numpy(tensor1)
tensor2

tensor([1., 2.], dtype=torch.float64)

In [ ]:
tensor2.device

device(type='cpu')

In [ ]:
tensor2_gpu = tensor2.to(device)
tensor2_gpu.device

device(type='cuda', index=0)

In [ ]:
tensor2.shape, tensor2_gpu.shape

(torch.Size([2]), torch.Size([2]))

In [ ]:
torch.matmul(tensor2_gpu, tensor2)

RuntimeError: Expected all tensors to be on the same device, but got tensor is on cpu, different from other tensors on cuda:0 (when checking argument in method wrapper_CUDA__dot)

In [ ]:
tensor2_back = tensor2_gpu.to(device="cpu")
tensor2_back.device

device(type='cpu')

In [ ]:
torch.matmul(tensor2_back, tensor2)

tensor(5., dtype=torch.float64)